services:
  chatbot:
    build: 
      context: .
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    container_name: chatbot-nodejs
    volumes:
      - ./logs:/app/logs
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    user: ${UID:-1000}:${GID:-1000}